"use client";

import type { Player } from "@/types/player.types";
import { motion } from "framer-motion";
import { Trophy, Share2, Loader2, Zap, Target, Skull } from "lucide-react";
import { formatBattleRating } from "./profile-helpers";
import { useFarcaster } from "@/store/farcaster-context";
import { toast } from "sonner";
import { useState } from "react";
import {
  RetroCard,
  RetroCardContent,
  RetroCardHeader,
  RetroCardTitle,
} from "@/components/ui/retro-card";
import { RetroButton } from "@/components/ui/retro-button";
import { cn } from "@/lib/utils";

interface BattleLegacyProps {
  character: Player;
  isOwner?: boolean;
}

export function BattleLegacy({
  character,
  isOwner = false,
}: BattleLegacyProps) {
  const { composeCast } = useFarcaster();
  const [isSharing, setIsSharing] = useState(false);

  const handleShare = async () => {
    if (!character) {
      toast.error("Cannot share: Character data not available.");
      return;
    }

    setIsSharing(true);

    try {
      const appDomain =
        process.env.NEXT_PUBLIC_APP_URL || window.location.origin;
      if (!appDomain) {
        toast.error("Application URL is not configured. Cannot share.");
        console.error("Share error: NEXT_PUBLIC_APP_URL is not defined.");
        return;
      }

      // Create the character page URL
      const characterUrl = `${appDomain}/character/${character.id}`;

      // Compose the cast with the character URL
      // The metadata and image will be automatically generated by the character page
      await composeCast({
        url: characterUrl,
        text: `Check out my Heavy Helms warrior: ${character.name.fullName}! 🛡️⚔️`,
      });

      toast.success(
        "Character shared successfully! Check your Farcaster client.",
      );
    } catch (error) {
      console.error("Failed to share character:", error);
      toast.error("Failed to share character. Please try again.");
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.2 }}
    >
      <RetroCard variant="arcade" withScanlines>
        <RetroCardHeader variant="arcade">
          <div className="flex items-center justify-between">
            <RetroCardTitle
              variant="arcade"
              className="font-pixel text-pixel-lg flex items-center gap-2"
            >
              <Trophy className="h-4 w-4 text-warning retro-box-glow" />
              BATTLE LEGACY
            </RetroCardTitle>

            {/* Share button - only visible to character owner */}
            {isOwner && (
              <RetroButton
                variant="pixel"
                size="sm"
                onClick={handleShare}
                disabled={isSharing}
                className="retro-glow"
                glow="subtle"
              >
                {isSharing ? (
                  <Loader2 className="h-3 w-3 animate-spin" />
                ) : (
                  <Share2 className="h-3 w-3" />
                )}
                <span className="hidden sm:inline font-pixel text-pixel-xs">
                  SHARE
                </span>
              </RetroButton>
            )}
          </div>
        </RetroCardHeader>

        <RetroCardContent className="p-4">
          <div className="grid grid-cols-5 gap-2">
            <RetroCompactStat
              label="RANK"
              value={character?.rank ? `#${character.rank}` : "N/A"}
              icon={<Trophy className="h-3 w-3" />}
              variant="warning"
            />
            <RetroCompactStat
              label="RATING"
              value={formatBattleRating(character.battleRating)}
              icon={<Zap className="h-3 w-3" />}
              variant="primary"
            />
            <RetroCompactStat
              label="WINS"
              value={character.record.wins.toString()}
              icon={<Target className="h-3 w-3" />}
              variant="success"
            />
            <RetroCompactStat
              label="LOSSES"
              value={character.record.losses.toString()}
              icon={<Skull className="h-3 w-3" />}
              variant="destructive"
            />
            <RetroCompactStat
              label="KILLS"
              value={character.record.kills.toString()}
              icon={<Zap className="h-3 w-3" />}
              variant="default"
            />
          </div>
        </RetroCardContent>
      </RetroCard>
    </motion.div>
  );
}

// Retro version of StatBox
function RetroCompactStat({
  label,
  value,
  icon,
  variant = "default",
}: {
  label: string;
  value: string;
  icon: React.ReactNode;
  variant?: "default" | "primary" | "success" | "warning" | "destructive";
}) {
  const getVariantStyles = () => {
    switch (variant) {
      case "primary":
        return "text-primary border-primary/30";
      case "success":
        return "text-success border-success/30";
      case "warning":
        return "text-warning border-warning/30";
      case "destructive":
        return "text-destructive border-destructive/30";
      default:
        return "text-foreground border-primary/20";
    }
  };

  return (
    <RetroCard variant="pixel" size="sm" className="text-center">
      <RetroCardContent className="p-2 space-y-1 flex flex-col items-center">
        <div className={cn("flex justify-center", getVariantStyles())}>
          {icon}
        </div>
        <div
          className={cn(
            "font-pixel text-pixel-sm font-bold",
            getVariantStyles(),
          )}
        >
          {value}
        </div>
        <div className="font-pixel text-pixel-xs text-foreground/70 uppercase">
          {label}
        </div>
      </RetroCardContent>
    </RetroCard>
  );
}
