"use client";

import type { Player } from "@/types/player.types";
import { motion } from "framer-motion";
import { Trophy, Share2, Loader2 } from "lucide-react";
import { formatBattleRating } from "./profile-helpers";
import { useFarcaster } from "@/store/farcaster-context";
import { toast } from "sonner";
import { useState } from "react";

interface BattleLegacyProps {
  character: Player;
  isOwner?: boolean;
}

export function BattleLegacy({
  character,
  isOwner = false,
}: BattleLegacyProps) {
  const { composeCast } = useFarcaster();
  const [isSharing, setIsSharing] = useState(false);

  const handleShare = async () => {
    if (!character) {
      toast.error("Cannot share: Character data not available.");
      return;
    }

    setIsSharing(true);

    try {
      const appDomain =
        process.env.NEXT_PUBLIC_APP_URL || window.location.origin;
      if (!appDomain) {
        toast.error("Application URL is not configured. Cannot share.");
        console.error("Share error: NEXT_PUBLIC_APP_URL is not defined.");
        return;
      }

      // Create the character page URL
      const characterUrl = `${appDomain}/character/${character.id}`;

      // Compose the cast with the character URL
      // The metadata and image will be automatically generated by the character page
      await composeCast({
        url: characterUrl,
        text: `Check out my Heavy Helms warrior: ${character.name.fullName}! 🛡️⚔️`,
      });

      toast.success(
        "Character shared successfully! Check your Farcaster client.",
      );
    } catch (error) {
      console.error("Failed to share character:", error);
      toast.error("Failed to share character. Please try again.");
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.2 }}
    >
      <div className="relative overflow-hidden">
        <div className="absolute bottom-0 left-0 w-16 h-16 bg-amber-700/5 rounded-full translate-y-1/2 -translate-x-1/2 blur-xl" />

        {/* Header with share button */}
        <div className="flex items-center justify-between mb-2 relative z-10">
          <h3 className="text-sm font-semibold text-yellow-500 flex items-center">
            <Trophy className="mr-1 h-3 w-3" />
            Battle Legacy
          </h3>

          {/* Share button - only visible to character owner */}
          {isOwner && (
            <button
              onClick={handleShare}
              disabled={isSharing}
              className="flex items-center gap-1 px-2 py-1 text-xs bg-blue-600/20 hover:bg-blue-600/30 border border-blue-500/30 rounded-md text-blue-400 hover:text-blue-300 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
              aria-label="Share character on Farcaster"
              type="button"
            >
              {isSharing ? (
                <Loader2 className="h-3 w-3 animate-spin" />
              ) : (
                <Share2 className="h-3 w-3" />
              )}
              <span className="hidden sm:inline">Share</span>
            </button>
          )}
        </div>

        <div className="grid grid-cols-5 gap-1 relative z-10">
          <CompactStat
            label="Rank"
            value={character?.rank ? `#${character.rank}` : "N/A"}
            className="text-amber-500"
          />
          <CompactStat
            label="Rating"
            value={formatBattleRating(character.battleRating)}
            className="text-yellow-400"
          />
          <CompactStat
            label="Wins"
            value={character.record.wins.toString()}
            className="text-green-400"
          />
          <CompactStat
            label="Losses"
            value={character.record.losses.toString()}
            className="text-red-400"
          />
          <CompactStat
            label="Kills"
            value={character.record.kills.toString()}
            className="text-stone-200"
          />
        </div>
      </div>
    </motion.div>
  );
}

// A more compact version of StatBox specifically for this component
function CompactStat({
  label,
  value,
  className = "",
}: { label: string; value: string; className?: string }) {
  return (
    <div className="text-center p-1 bg-stone-800/30 rounded border border-yellow-600/10">
      <div className={`text-sm font-semibold ${className}`}>{value}</div>
      <div className="text-stone-400 text-xs">{label}</div>
    </div>
  );
}
