export const DuelGameABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_gameEngine", type: "address", internalType: "address" },
      { name: "_playerContract", type: "address", internalType: "address" },
      {
        name: "_defaultPlayerContract",
        type: "address",
        internalType: "address",
      },
      { name: "_monsterContract", type: "address", internalType: "address" },
      { name: "operator", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "BLOCKS_UNTIL_EXPIRE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BLOCKS_UNTIL_WITHDRAW",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acceptChallenge",
    inputs: [
      { name: "challengeId", type: "uint256", internalType: "uint256" },
      {
        name: "defenderLoadout",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "calculateFee",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelChallenge",
    inputs: [{ name: "challengeId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "challenges",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "challengerId", type: "uint32", internalType: "uint32" },
      { name: "defenderId", type: "uint32", internalType: "uint32" },
      { name: "wagerAmount", type: "uint256", internalType: "uint256" },
      { name: "createdBlock", type: "uint256", internalType: "uint256" },
      {
        name: "challengerLoadout",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
        ],
      },
      {
        name: "defenderLoadout",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
        ],
      },
      { name: "fulfilled", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultPlayerContract",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IDefaultPlayer" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forceCloseAbandonedChallenge",
    inputs: [{ name: "challengeId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fulfillRandomness",
    inputs: [
      { name: "randomness", type: "uint256", internalType: "uint256" },
      { name: "dataWithRound", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "gameEngine",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IGameEngine" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserActiveChallenges",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasPendingRequest",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initiateChallenge",
    inputs: [
      {
        name: "challengerLoadout",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
        ],
      },
      { name: "defenderId", type: "uint32", internalType: "uint32" },
      { name: "wagerAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "isChallengeActive",
    inputs: [{ name: "challengeId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isGameEnabled",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxWagerAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minDuelFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minWagerAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "monsterContract",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IMonster" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextChallengeId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerContract",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IPlayer" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestPending",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestToChallengeId",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestedHash",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setDefaultPlayerContract",
    inputs: [
      { name: "_newContract", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGameEnabled",
    inputs: [{ name: "enabled", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGameEngine",
    inputs: [{ name: "_newEngine", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinDuelFee",
    inputs: [{ name: "_minDuelFee", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinWagerAmount",
    inputs: [
      { name: "_minWagerAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMonsterContract",
    inputs: [
      { name: "_newContract", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [{ name: "newOperator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlayerContract",
    inputs: [
      { name: "_newContract", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setWagerFeePercentage",
    inputs: [
      { name: "_wagerFeePercentage", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalFeesCollected",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userChallenges",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "wagerFeePercentage",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawFees",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ChallengeAccepted",
    inputs: [
      {
        name: "challengeId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "defenderId",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChallengeCancelled",
    inputs: [
      {
        name: "challengeId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChallengeCreated",
    inputs: [
      {
        name: "challengeId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "challengerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "defenderId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "wagerAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "createdAtBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChallengeExpired",
    inputs: [
      {
        name: "challengeId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChallengeForfeited",
    inputs: [
      {
        name: "challengeId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CombatResult",
    inputs: [
      {
        name: "player1Data",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "player2Data",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "winningPlayerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "packedResults",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultPlayerContractUpdated",
    inputs: [
      {
        name: "oldContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DuelComplete",
    inputs: [
      {
        name: "challengeId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "winnerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "randomSeed",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "winnerPayout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeesWithdrawn",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameEnabledUpdated",
    inputs: [
      { name: "enabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameEngineUpdated",
    inputs: [
      {
        name: "oldEngine",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newEngine",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MinDuelFeeUpdated",
    inputs: [
      {
        name: "oldFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MinWagerAmountUpdated",
    inputs: [
      {
        name: "newAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MonsterContractUpdated",
    inputs: [
      {
        name: "oldContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerContractUpdated",
    inputs: [
      {
        name: "oldContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestedRandomness",
    inputs: [
      {
        name: "round",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "data", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WagerFeePercentageUpdated",
    inputs: [
      {
        name: "oldPercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newPercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
