export const DuelGameABI = [
  {
    inputs: [
      { internalType: "address", name: "_gameEngine", type: "address" },
      { internalType: "address", name: "_playerContract", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "challengeId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "defenderId",
        type: "uint32",
      },
    ],
    name: "ChallengeAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "challengeId",
        type: "uint256",
      },
    ],
    name: "ChallengeCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "challengeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "challengerId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "defenderId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wagerAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "createdAtBlock",
        type: "uint256",
      },
    ],
    name: "ChallengeCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "challengeId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ChallengeForfeited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "challengeId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "challengerRefund",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "defenderRefund",
        type: "uint256",
      },
    ],
    name: "ChallengeRecovered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "player1Data",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "player2Data",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "winningPlayerId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "packedResults",
        type: "bytes",
      },
    ],
    name: "CombatResult",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "challengeId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "winnerId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "randomness",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "winnerPayout",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeCollected",
        type: "uint256",
      },
    ],
    name: "DuelComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FeesWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "GameEnabledUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldEngine",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newEngine",
        type: "address",
      },
    ],
    name: "GameEngineUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newFee",
        type: "uint256",
      },
    ],
    name: "MinDuelFeeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newAmount",
        type: "uint256",
      },
    ],
    name: "MinWagerAmountUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newContract",
        type: "address",
      },
    ],
    name: "PlayerContractUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "round",
        type: "uint256",
      },
      { indexed: false, internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "RequestedRandomness",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldValue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "TimeUntilExpireUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldValue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "TimeUntilWithdrawUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldValue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "VrfRequestTimeoutUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldPercentage",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newPercentage",
        type: "uint256",
      },
    ],
    name: "WagerFeePercentageUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "enabled", type: "bool" },
    ],
    name: "WagersEnabledUpdated",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "challengeId", type: "uint256" },
      {
        components: [
          { internalType: "uint32", name: "playerId", type: "uint32" },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
        ],
        internalType: "struct Fighter.PlayerLoadout",
        name: "defenderLoadout",
        type: "tuple",
      },
    ],
    name: "acceptChallenge",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "calculateFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "cancelChallenge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "challenges",
    outputs: [
      { internalType: "uint32", name: "challengerId", type: "uint32" },
      { internalType: "uint32", name: "defenderId", type: "uint32" },
      { internalType: "uint256", name: "wagerAmount", type: "uint256" },
      { internalType: "uint256", name: "createdBlock", type: "uint256" },
      { internalType: "uint256", name: "createdTimestamp", type: "uint256" },
      { internalType: "uint256", name: "vrfRequestTimestamp", type: "uint256" },
      {
        components: [
          { internalType: "uint32", name: "playerId", type: "uint32" },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
        ],
        internalType: "struct Fighter.PlayerLoadout",
        name: "challengerLoadout",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint32", name: "playerId", type: "uint32" },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
        ],
        internalType: "struct Fighter.PlayerLoadout",
        name: "defenderLoadout",
        type: "tuple",
      },
      {
        internalType: "enum DuelGame.ChallengeState",
        name: "state",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "forceCloseAbandonedChallenge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "randomness", type: "uint256" },
      { internalType: "bytes", name: "dataWithRound", type: "bytes" },
    ],
    name: "fulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gameEngine",
    outputs: [
      { internalType: "contract IGameEngine", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint32", name: "playerId", type: "uint32" },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
        ],
        internalType: "struct Fighter.PlayerLoadout",
        name: "challengerLoadout",
        type: "tuple",
      },
      { internalType: "uint32", name: "defenderId", type: "uint32" },
      { internalType: "uint256", name: "wagerAmount", type: "uint256" },
    ],
    name: "initiateChallenge",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "isChallengeActive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "isChallengeCompleted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "isChallengeExpired",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "isChallengePending",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isGameEnabled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxWagerAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minDuelFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minWagerAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextChallengeId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "playerContract",
    outputs: [{ internalType: "contract IPlayer", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "challengeId", type: "uint256" }],
    name: "recoverTimedOutVRF",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "requestPending",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "requestToChallengeId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "requestedHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "enabled", type: "bool" }],
    name: "setGameEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newEngine", type: "address" }],
    name: "setGameEngine",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_minDuelFee", type: "uint256" }],
    name: "setMinDuelFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_minWagerAmount", type: "uint256" },
    ],
    name: "setMinWagerAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOperator", type: "address" }],
    name: "setOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_newContract", type: "address" },
    ],
    name: "setPlayerContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newValue", type: "uint256" }],
    name: "setTimeUntilExpire",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newValue", type: "uint256" }],
    name: "setTimeUntilWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newValue", type: "uint256" }],
    name: "setVrfRequestTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_wagerFeePercentage", type: "uint256" },
    ],
    name: "setWagerFeePercentage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "enabled", type: "bool" }],
    name: "setWagersEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "timeUntilExpire",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timeUntilWithdraw",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalFeesCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "vrfRequestTimeout",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "wagerFeePercentage",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "wagersEnabled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
