export const GameEngineABI = [
  {
    type: "function",
    name: "ARMOR_CHAIN",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ARMOR_CLOTH",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ARMOR_LEATHER",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ARMOR_PLATE",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BALANCED_STANCE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.StanceMultiplier",
        components: [
          { name: "damageModifier", type: "uint16", internalType: "uint16" },
          { name: "hitChance", type: "uint16", internalType: "uint16" },
          { name: "critChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "blockChance", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "dodgeChance", type: "uint16", internalType: "uint16" },
          { name: "counterChance", type: "uint16", internalType: "uint16" },
          {
            name: "staminaCostModifier",
            type: "uint16",
            internalType: "uint16",
          },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "BATTLEAXE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "CHAIN",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.ArmorStats",
        components: [
          { name: "defense", type: "uint16", internalType: "uint16" },
          { name: "weight", type: "uint16", internalType: "uint16" },
          { name: "slashResist", type: "uint16", internalType: "uint16" },
          { name: "pierceResist", type: "uint16", internalType: "uint16" },
          { name: "bluntResist", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "CLOTH",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.ArmorStats",
        components: [
          { name: "defense", type: "uint16", internalType: "uint16" },
          { name: "weight", type: "uint16", internalType: "uint16" },
          { name: "slashResist", type: "uint16", internalType: "uint16" },
          { name: "pierceResist", type: "uint16", internalType: "uint16" },
          { name: "bluntResist", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "DEFENSIVE_STANCE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.StanceMultiplier",
        components: [
          { name: "damageModifier", type: "uint16", internalType: "uint16" },
          { name: "hitChance", type: "uint16", internalType: "uint16" },
          { name: "critChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "blockChance", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "dodgeChance", type: "uint16", internalType: "uint16" },
          { name: "counterChance", type: "uint16", internalType: "uint16" },
          {
            name: "staminaCostModifier",
            type: "uint16",
            internalType: "uint16",
          },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "GREATSWORD",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "LEATHER",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.ArmorStats",
        components: [
          { name: "defense", type: "uint16", internalType: "uint16" },
          { name: "weight", type: "uint16", internalType: "uint16" },
          { name: "slashResist", type: "uint16", internalType: "uint16" },
          { name: "pierceResist", type: "uint16", internalType: "uint16" },
          { name: "bluntResist", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "MACE_AND_SHIELD",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "OFFENSIVE_STANCE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.StanceMultiplier",
        components: [
          { name: "damageModifier", type: "uint16", internalType: "uint16" },
          { name: "hitChance", type: "uint16", internalType: "uint16" },
          { name: "critChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "blockChance", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "dodgeChance", type: "uint16", internalType: "uint16" },
          { name: "counterChance", type: "uint16", internalType: "uint16" },
          {
            name: "staminaCostModifier",
            type: "uint16",
            internalType: "uint16",
          },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "PLATE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.ArmorStats",
        components: [
          { name: "defense", type: "uint16", internalType: "uint16" },
          { name: "weight", type: "uint16", internalType: "uint16" },
          { name: "slashResist", type: "uint16", internalType: "uint16" },
          { name: "pierceResist", type: "uint16", internalType: "uint16" },
          { name: "bluntResist", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "QUARTERSTAFF",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "RAPIER_AND_SHIELD",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "SPEAR",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "STANCE_BALANCED",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STANCE_DEFENSIVE",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STANCE_OFFENSIVE",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SWORD_AND_SHIELD",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "WEAPON_BATTLEAXE",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEAPON_GREATSWORD",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEAPON_MACE_AND_SHIELD",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEAPON_QUARTERSTAFF",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEAPON_RAPIER_AND_SHIELD",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEAPON_SPEAR",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WEAPON_SWORD_AND_SHIELD",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateStats",
    inputs: [
      {
        name: "player",
        type: "tuple",
        internalType: "struct IGameEngine.FighterStats",
        components: [
          { name: "weapon", type: "uint8", internalType: "uint8" },
          { name: "armor", type: "uint8", internalType: "uint8" },
          { name: "stance", type: "uint8", internalType: "uint8" },
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.CalculatedStats",
        components: [
          { name: "maxHealth", type: "uint16", internalType: "uint16" },
          { name: "damageModifier", type: "uint16", internalType: "uint16" },
          { name: "hitChance", type: "uint16", internalType: "uint16" },
          { name: "blockChance", type: "uint16", internalType: "uint16" },
          { name: "dodgeChance", type: "uint16", internalType: "uint16" },
          { name: "maxEndurance", type: "uint16", internalType: "uint16" },
          { name: "critChance", type: "uint16", internalType: "uint16" },
          { name: "initiative", type: "uint16", internalType: "uint16" },
          { name: "counterChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "baseSurvivalRate", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "decodeCombatLog",
    inputs: [{ name: "results", type: "bytes", internalType: "bytes" }],
    outputs: [
      { name: "player1Won", type: "bool", internalType: "bool" },
      { name: "gameEngineVersion", type: "uint16", internalType: "uint16" },
      {
        name: "condition",
        type: "uint8",
        internalType: "enum IGameEngine.WinCondition",
      },
      {
        name: "actions",
        type: "tuple[]",
        internalType: "struct IGameEngine.CombatAction[]",
        components: [
          {
            name: "p1Result",
            type: "uint8",
            internalType: "enum IGameEngine.CombatResultType",
          },
          { name: "p1Damage", type: "uint16", internalType: "uint16" },
          { name: "p1StaminaLost", type: "uint8", internalType: "uint8" },
          {
            name: "p2Result",
            type: "uint8",
            internalType: "enum IGameEngine.CombatResultType",
          },
          { name: "p2Damage", type: "uint16", internalType: "uint16" },
          { name: "p2StaminaLost", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "decodeVersion",
    inputs: [{ name: "_version", type: "uint16", internalType: "uint16" }],
    outputs: [
      { name: "major", type: "uint8", internalType: "uint8" },
      { name: "minor", type: "uint8", internalType: "uint8" },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getArmorStats",
    inputs: [{ name: "armor", type: "uint8", internalType: "uint8" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.ArmorStats",
        components: [
          { name: "defense", type: "uint16", internalType: "uint16" },
          { name: "weight", type: "uint16", internalType: "uint16" },
          { name: "slashResist", type: "uint16", internalType: "uint16" },
          { name: "pierceResist", type: "uint16", internalType: "uint16" },
          { name: "bluntResist", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getStanceMultiplier",
    inputs: [{ name: "stance", type: "uint8", internalType: "uint8" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.StanceMultiplier",
        components: [
          { name: "damageModifier", type: "uint16", internalType: "uint16" },
          { name: "hitChance", type: "uint16", internalType: "uint16" },
          { name: "critChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "blockChance", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "dodgeChance", type: "uint16", internalType: "uint16" },
          { name: "counterChance", type: "uint16", internalType: "uint16" },
          {
            name: "staminaCostModifier",
            type: "uint16",
            internalType: "uint16",
          },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getWeaponStats",
    inputs: [{ name: "weapon", type: "uint8", internalType: "uint8" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GameEngine.WeaponStats",
        components: [
          { name: "minDamage", type: "uint16", internalType: "uint16" },
          { name: "maxDamage", type: "uint16", internalType: "uint16" },
          { name: "attackSpeed", type: "uint16", internalType: "uint16" },
          { name: "parryChance", type: "uint16", internalType: "uint16" },
          { name: "riposteChance", type: "uint16", internalType: "uint16" },
          { name: "critMultiplier", type: "uint16", internalType: "uint16" },
          { name: "staminaMultiplier", type: "uint16", internalType: "uint16" },
          { name: "survivalFactor", type: "uint16", internalType: "uint16" },
          {
            name: "damageType",
            type: "uint8",
            internalType: "enum GameEngine.DamageType",
          },
          { name: "isTwoHanded", type: "bool", internalType: "bool" },
          { name: "hasShield", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "processGame",
    inputs: [
      {
        name: "player1",
        type: "tuple",
        internalType: "struct IGameEngine.FighterStats",
        components: [
          { name: "weapon", type: "uint8", internalType: "uint8" },
          { name: "armor", type: "uint8", internalType: "uint8" },
          { name: "stance", type: "uint8", internalType: "uint8" },
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
        ],
      },
      {
        name: "player2",
        type: "tuple",
        internalType: "struct IGameEngine.FighterStats",
        components: [
          { name: "weapon", type: "uint8", internalType: "uint8" },
          { name: "armor", type: "uint8", internalType: "uint8" },
          { name: "stance", type: "uint8", internalType: "uint8" },
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
        ],
      },
      { name: "randomSeed", type: "uint256", internalType: "uint256" },
      { name: "lethalityFactor", type: "uint16", internalType: "uint16" },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
] as const;
