export const GauntletGameABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_gameEngine", type: "address", internalType: "address" },
      { name: "_playerContract", type: "address", internalType: "address" },
      {
        name: "_defaultPlayerAddress",
        type: "address",
        internalType: "address",
      },
      { name: "_operatorAddr", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "contractFeesCollected",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentEntryFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentGauntletSize",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultPlayerContract",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IDefaultPlayer" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feePercentage",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fulfillRandomness",
    inputs: [
      { name: "randomness", type: "uint256", internalType: "uint256" },
      { name: "dataWithRound", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "gameEngine",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IGameEngine" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gauntlets",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "size", type: "uint8", internalType: "uint8" },
      { name: "entryFee", type: "uint256", internalType: "uint256" },
      {
        name: "state",
        type: "uint8",
        internalType: "enum GauntletGame.GauntletState",
      },
      { name: "vrfRequestId", type: "uint256", internalType: "uint256" },
      { name: "vrfRequestTimestamp", type: "uint256", internalType: "uint256" },
      { name: "completionTimestamp", type: "uint256", internalType: "uint256" },
      { name: "championId", type: "uint32", internalType: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGauntletData",
    inputs: [{ name: "gauntletId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GauntletGame.Gauntlet",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "size", type: "uint8", internalType: "uint8" },
          { name: "entryFee", type: "uint256", internalType: "uint256" },
          {
            name: "state",
            type: "uint8",
            internalType: "enum GauntletGame.GauntletState",
          },
          { name: "vrfRequestId", type: "uint256", internalType: "uint256" },
          {
            name: "vrfRequestTimestamp",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "completionTimestamp",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "participants",
            type: "tuple[]",
            internalType: "struct GauntletGame.RegisteredPlayer[]",
            components: [
              { name: "playerId", type: "uint32", internalType: "uint32" },
              {
                name: "loadout",
                type: "tuple",
                internalType: "struct Fighter.PlayerLoadout",
                components: [
                  { name: "playerId", type: "uint32", internalType: "uint32" },
                  {
                    name: "skin",
                    type: "tuple",
                    internalType: "struct Fighter.SkinInfo",
                    components: [
                      {
                        name: "skinIndex",
                        type: "uint32",
                        internalType: "uint32",
                      },
                      {
                        name: "skinTokenId",
                        type: "uint16",
                        internalType: "uint16",
                      },
                    ],
                  },
                  { name: "stance", type: "uint8", internalType: "uint8" },
                ],
              },
            ],
          },
          { name: "winners", type: "uint32[]", internalType: "uint32[]" },
          { name: "championId", type: "uint32", internalType: "uint32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerLoadoutFromQueue",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
          { name: "stance", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQueueSize",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isGameEnabled",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastGauntletStartTime",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxDefaultPlayerSubstituteId",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minTimeBetweenGauntlets",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextGauntletId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerContract",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IPlayer" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerCurrentGauntlet",
    inputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerIndexInQueue",
    inputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerStatus",
    inputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum GauntletGame.PlayerStatus",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queueForGauntlet",
    inputs: [
      {
        name: "loadout",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
          { name: "stance", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "queueIndex",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queuedFeesPool",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recoverTimedOutVRF",
    inputs: [{ name: "gauntletId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registrationQueue",
    inputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    outputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      {
        name: "skin",
        type: "tuple",
        internalType: "struct Fighter.SkinInfo",
        components: [
          { name: "skinIndex", type: "uint32", internalType: "uint32" },
          { name: "skinTokenId", type: "uint16", internalType: "uint16" },
        ],
      },
      { name: "stance", type: "uint8", internalType: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestPending",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestToGauntletId",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestedHash",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setDefaultPlayerContract",
    inputs: [{ name: "newAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEntryFee",
    inputs: [{ name: "newFee", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeePercentage",
    inputs: [
      { name: "_newFeePercentage", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGameEnabled",
    inputs: [{ name: "enabled", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGameEngine",
    inputs: [{ name: "_newEngine", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGauntletSize",
    inputs: [{ name: "newSize", type: "uint8", internalType: "uint8" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxDefaultPlayerSubstituteId",
    inputs: [{ name: "_maxId", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinTimeBetweenGauntlets",
    inputs: [{ name: "newMinTime", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [{ name: "newOperator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlayerContract",
    inputs: [
      { name: "_newContract", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tryStartGauntlet",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vrfRequestTimeout",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawFees",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawFromQueue",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CombatResult",
    inputs: [
      {
        name: "player1Data",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "player2Data",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "winningPlayerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "packedResults",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultPlayerContractSet",
    inputs: [
      {
        name: "newContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EntryFeeSet",
    inputs: [
      {
        name: "oldFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeePercentageSet",
    inputs: [
      {
        name: "oldPercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newPercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeesWithdrawn",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameEnabledUpdated",
    inputs: [
      { name: "enabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameEngineUpdated",
    inputs: [
      {
        name: "oldEngine",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newEngine",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GauntletCompleted",
    inputs: [
      {
        name: "gauntletId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "size", type: "uint8", indexed: false, internalType: "uint8" },
      {
        name: "entryFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "championId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "prizeAwarded",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "feeCollected",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "participantIds",
        type: "uint32[]",
        indexed: false,
        internalType: "uint32[]",
      },
      {
        name: "roundWinners",
        type: "uint32[]",
        indexed: false,
        internalType: "uint32[]",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GauntletRecovered",
    inputs: [
      {
        name: "gauntletId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GauntletSizeSet",
    inputs: [
      { name: "oldSize", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "newSize", type: "uint8", indexed: false, internalType: "uint8" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GauntletStarted",
    inputs: [
      {
        name: "gauntletId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "size", type: "uint8", indexed: false, internalType: "uint8" },
      {
        name: "entryFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "participants",
        type: "tuple[]",
        indexed: false,
        internalType: "struct GauntletGame.RegisteredPlayer[]",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "loadout",
            type: "tuple",
            internalType: "struct Fighter.PlayerLoadout",
            components: [
              { name: "playerId", type: "uint32", internalType: "uint32" },
              {
                name: "skin",
                type: "tuple",
                internalType: "struct Fighter.SkinInfo",
                components: [
                  { name: "skinIndex", type: "uint32", internalType: "uint32" },
                  {
                    name: "skinTokenId",
                    type: "uint16",
                    internalType: "uint16",
                  },
                ],
              },
              { name: "stance", type: "uint8", internalType: "uint8" },
            ],
          },
        ],
      },
      {
        name: "vrfRequestId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MaxDefaultPlayerSubstituteIdSet",
    inputs: [
      {
        name: "newMaxId",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MinTimeBetweenGauntletsSet",
    inputs: [
      {
        name: "newMinTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OperatorSet",
    inputs: [
      {
        name: "newOperator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerContractUpdated",
    inputs: [
      {
        name: "oldContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerQueued",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "queueSize",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "entryFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerWithdrew",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "queueSize",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "QueueClearedDueToGameDisabled",
    inputs: [
      {
        name: "playerIds",
        type: "uint32[]",
        indexed: false,
        internalType: "uint32[]",
      },
      {
        name: "totalRefunded",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "QueueClearedDueToSettingsChange",
    inputs: [
      {
        name: "playersRefunded",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalRefunded",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestedRandomness",
    inputs: [
      {
        name: "round",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "data", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyInQueue", inputs: [] },
  { type: "error", name: "CallerNotPlayerOwner", inputs: [] },
  { type: "error", name: "GameDisabled", inputs: [] },
  { type: "error", name: "GauntletDoesNotExist", inputs: [] },
  { type: "error", name: "GauntletNotPending", inputs: [] },
  {
    type: "error",
    name: "IncorrectEntryFee",
    inputs: [
      { name: "expected", type: "uint256", internalType: "uint256" },
      { name: "actual", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientQueueSize",
    inputs: [
      { name: "current", type: "uint256", internalType: "uint256" },
      { name: "required", type: "uint8", internalType: "uint8" },
    ],
  },
  { type: "error", name: "InvalidDefaultPlayerRange", inputs: [] },
  {
    type: "error",
    name: "InvalidGauntletSize",
    inputs: [{ name: "size", type: "uint8", internalType: "uint8" }],
  },
  { type: "error", name: "InvalidLoadout", inputs: [] },
  { type: "error", name: "InvalidSkin", inputs: [] },
  { type: "error", name: "MinTimeNotElapsed", inputs: [] },
  { type: "error", name: "NoFeesToWithdraw", inputs: [] },
  { type: "error", name: "PlayerIsRetired", inputs: [] },
  { type: "error", name: "PlayerNotInQueue", inputs: [] },
  { type: "error", name: "TimeoutNotReached", inputs: [] },
  { type: "error", name: "UnsupportedPlayerId", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
