export const PlayerABI = [
  {
    type: "constructor",
    inputs: [
      { name: "skinRegistryAddress", type: "address", internalType: "address" },
      { name: "nameRegistryAddress", type: "address", internalType: "address" },
      {
        name: "equipmentRequirementsAddress",
        type: "address",
        internalType: "address",
      },
      { name: "operator", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BASE_PLAYER_SLOTS",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attributeSwapCharges",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "awardAttributeSwap",
    inputs: [{ name: "to", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "awardNameChange",
    inputs: [{ name: "to", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeName",
    inputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      { name: "firstNameIndex", type: "uint16", internalType: "uint16" },
      { name: "surnameIndex", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "clearPendingRequestsForAddress",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "convertToFighterStats",
    inputs: [
      {
        name: "loadout",
        type: "tuple",
        internalType: "struct Fighter.PlayerLoadout",
        components: [
          { name: "playerId", type: "uint32", internalType: "uint32" },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IGameEngine.FighterStats",
        components: [
          { name: "weapon", type: "uint8", internalType: "uint8" },
          { name: "armor", type: "uint8", internalType: "uint8" },
          { name: "stance", type: "uint8", internalType: "uint8" },
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createPlayerFeeAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decodePlayerData",
    inputs: [{ name: "data", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      {
        name: "stats",
        type: "tuple",
        internalType: "struct IPlayer.PlayerStats",
        components: [
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
          { name: "firstNameIndex", type: "uint16", internalType: "uint16" },
          { name: "surnameIndex", type: "uint16", internalType: "uint16" },
          { name: "wins", type: "uint16", internalType: "uint16" },
          { name: "losses", type: "uint16", internalType: "uint16" },
          { name: "kills", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "encodePlayerData",
    inputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      {
        name: "stats",
        type: "tuple",
        internalType: "struct IPlayer.PlayerStats",
        components: [
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
          { name: "firstNameIndex", type: "uint16", internalType: "uint16" },
          { name: "surnameIndex", type: "uint16", internalType: "uint16" },
          { name: "wins", type: "uint16", internalType: "uint16" },
          { name: "losses", type: "uint16", internalType: "uint16" },
          { name: "kills", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "equipSkin",
    inputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      { name: "skinIndex", type: "uint32", internalType: "uint32" },
      { name: "skinTokenId", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "equipmentRequirements",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IEquipmentRequirements",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fulfillRandomness",
    inputs: [
      { name: "randomness", type: "uint256", internalType: "uint256" },
      { name: "dataWithRound", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "gameContractPermissions",
    inputs: [
      { name: "gameContract", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IPlayer.GamePermissions",
        components: [
          { name: "record", type: "bool", internalType: "bool" },
          { name: "retire", type: "bool", internalType: "bool" },
          { name: "name", type: "bool", internalType: "bool" },
          { name: "attributes", type: "bool", internalType: "bool" },
          { name: "immortal", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActivePlayerCount",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentSkin",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Fighter.SkinInfo",
        components: [
          { name: "skinIndex", type: "uint32", internalType: "uint32" },
          { name: "skinTokenId", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFighterStats",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IGameEngine.FighterStats",
        components: [
          { name: "weapon", type: "uint8", internalType: "uint8" },
          { name: "armor", type: "uint8", internalType: "uint8" },
          { name: "stance", type: "uint8", internalType: "uint8" },
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNextSlotBatchCost",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingRequest",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayer",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IPlayer.PlayerStats",
        components: [
          {
            name: "attributes",
            type: "tuple",
            internalType: "struct Fighter.Attributes",
            components: [
              { name: "strength", type: "uint8", internalType: "uint8" },
              { name: "constitution", type: "uint8", internalType: "uint8" },
              { name: "size", type: "uint8", internalType: "uint8" },
              { name: "agility", type: "uint8", internalType: "uint8" },
              { name: "stamina", type: "uint8", internalType: "uint8" },
              { name: "luck", type: "uint8", internalType: "uint8" },
            ],
          },
          {
            name: "skin",
            type: "tuple",
            internalType: "struct Fighter.SkinInfo",
            components: [
              { name: "skinIndex", type: "uint32", internalType: "uint32" },
              { name: "skinTokenId", type: "uint16", internalType: "uint16" },
            ],
          },
          { name: "firstNameIndex", type: "uint16", internalType: "uint16" },
          { name: "surnameIndex", type: "uint16", internalType: "uint16" },
          { name: "wins", type: "uint16", internalType: "uint16" },
          { name: "losses", type: "uint16", internalType: "uint16" },
          { name: "kills", type: "uint16", internalType: "uint16" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerIds",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint32[]", internalType: "uint32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerOwner",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerSlots",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRequestStatus",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "fulfilled", type: "bool", internalType: "bool" },
      { name: "owner", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "incrementKills",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "incrementLosses",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "incrementWins",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isPaused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPlayerImmortal",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPlayerRetired",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isValidId",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "nameChangeCharges",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nameRegistry",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPlayerNameRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "purchasePlayerSlots",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "recoverERC20",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestCreatePlayer",
    inputs: [{ name: "useNameSetB", type: "bool", internalType: "bool" }],
    outputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "requestPending",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestedHash",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "retireOwnPlayer",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreatePlayerFeeAmount",
    inputs: [
      { name: "newFeeAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEquipmentRequirements",
    inputs: [{ name: "newAddress", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGameContractPermission",
    inputs: [
      { name: "gameContract", type: "address", internalType: "address" },
      {
        name: "permissions",
        type: "tuple",
        internalType: "struct IPlayer.GamePermissions",
        components: [
          { name: "record", type: "bool", internalType: "bool" },
          { name: "retire", type: "bool", internalType: "bool" },
          { name: "name", type: "bool", internalType: "bool" },
          { name: "attributes", type: "bool", internalType: "bool" },
          { name: "immortal", type: "bool", internalType: "bool" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [{ name: "newOperator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPaused",
    inputs: [{ name: "paused", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlayerImmortal",
    inputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      { name: "immortal", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlayerRetired",
    inputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      { name: "retired", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSlotBatchCost",
    inputs: [{ name: "newCost", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "skinRegistry",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPlayerSkinRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "slotBatchCost",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "swapAttributes",
    inputs: [
      { name: "playerId", type: "uint32", internalType: "uint32" },
      {
        name: "decreaseAttribute",
        type: "uint8",
        internalType: "enum IPlayer.Attribute",
      },
      {
        name: "increaseAttribute",
        type: "uint8",
        internalType: "enum IPlayer.Attribute",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawFees",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AttributeSwapAwarded",
    inputs: [
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "totalCharges",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreatePlayerFeeUpdated",
    inputs: [
      {
        name: "oldFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EquipmentRequirementsUpdated",
    inputs: [
      {
        name: "oldAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameContractPermissionsUpdated",
    inputs: [
      {
        name: "gameContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "permissions",
        type: "tuple",
        indexed: false,
        internalType: "struct IPlayer.GamePermissions",
        components: [
          { name: "record", type: "bool", internalType: "bool" },
          { name: "retire", type: "bool", internalType: "bool" },
          { name: "name", type: "bool", internalType: "bool" },
          { name: "attributes", type: "bool", internalType: "bool" },
          { name: "immortal", type: "bool", internalType: "bool" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NameChangeAwarded",
    inputs: [
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "totalCharges",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PausedStateChanged",
    inputs: [
      { name: "isPaused", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerAttributesSwapped",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "decreaseAttribute",
        type: "uint8",
        indexed: false,
        internalType: "enum IPlayer.Attribute",
      },
      {
        name: "increaseAttribute",
        type: "uint8",
        indexed: false,
        internalType: "enum IPlayer.Attribute",
      },
      {
        name: "newDecreaseValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "newIncreaseValue",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerAttributesUpdated",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "strength",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "constitution",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      { name: "size", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "agility", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "stamina", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "luck", type: "uint8", indexed: false, internalType: "uint8" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerCreated",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "firstNameIndex",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "surnameIndex",
        type: "uint16",
        indexed: true,
        internalType: "uint16",
      },
      {
        name: "strength",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "constitution",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      { name: "size", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "agility", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "stamina", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "luck", type: "uint8", indexed: false, internalType: "uint8" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerCreationFulfilled",
    inputs: [
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "randomness",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerCreationRequested",
    inputs: [
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "requester",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerImmortalityChanged",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "immortal", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerKillUpdated",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      { name: "kills", type: "uint16", indexed: false, internalType: "uint16" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerNameUpdated",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "firstNameIndex",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "surnameIndex",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerRetired",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "retired", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerSkinEquipped",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "skinIndex",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      {
        name: "tokenId",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerSlotsPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "slotsAdded",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "totalSlots",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
      {
        name: "amountPaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlayerWinLossUpdated",
    inputs: [
      {
        name: "playerId",
        type: "uint32",
        indexed: true,
        internalType: "uint32",
      },
      { name: "wins", type: "uint16", indexed: false, internalType: "uint16" },
      {
        name: "losses",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RequestedRandomness",
    inputs: [
      {
        name: "round",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "data", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SlotBatchCostUpdated",
    inputs: [
      {
        name: "oldCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newCost",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BadZeroAddress", inputs: [] },
  { type: "error", name: "ContractPaused", inputs: [] },
  { type: "error", name: "InsufficientCharges", inputs: [] },
  { type: "error", name: "InsufficientFeeAmount", inputs: [] },
  { type: "error", name: "InvalidAttributeSwap", inputs: [] },
  { type: "error", name: "InvalidNameIndex", inputs: [] },
  { type: "error", name: "InvalidPlayerRange", inputs: [] },
  { type: "error", name: "InvalidRequestID", inputs: [] },
  { type: "error", name: "NoPermission", inputs: [] },
  { type: "error", name: "NotPlayerOwner", inputs: [] },
  { type: "error", name: "PendingRequestExists", inputs: [] },
  {
    type: "error",
    name: "PlayerDoesNotExist",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
  },
  {
    type: "error",
    name: "PlayerIsRetired",
    inputs: [{ name: "playerId", type: "uint32", internalType: "uint32" }],
  },
  { type: "error", name: "RequestAlreadyFulfilled", inputs: [] },
  { type: "error", name: "TooManyPlayers", inputs: [] },
] as const;
