export const PlayerABI = [
  {
    inputs: [
      { internalType: "address", name: "skinRegistryAddress", type: "address" },
      { internalType: "address", name: "nameRegistryAddress", type: "address" },
      {
        internalType: "address",
        name: "equipmentRequirementsAddress",
        type: "address",
      },
      { internalType: "address", name: "operator", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "BadZeroAddress", type: "error" },
  { inputs: [], name: "ContractPaused", type: "error" },
  { inputs: [], name: "InsufficientCharges", type: "error" },
  { inputs: [], name: "InsufficientFeeAmount", type: "error" },
  { inputs: [], name: "InvalidAttributeSwap", type: "error" },
  { inputs: [], name: "InvalidNameIndex", type: "error" },
  { inputs: [], name: "InvalidPlayerRange", type: "error" },
  { inputs: [], name: "InvalidRequestID", type: "error" },
  { inputs: [], name: "NoPendingRequest", type: "error" },
  { inputs: [], name: "NoPermission", type: "error" },
  { inputs: [], name: "NotPlayerOwner", type: "error" },
  { inputs: [], name: "PendingRequestExists", type: "error" },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "PlayerDoesNotExist",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "PlayerIsRetired",
    type: "error",
  },
  { inputs: [], name: "RequestAlreadyFulfilled", type: "error" },
  { inputs: [], name: "TooManyPlayers", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalCharges",
        type: "uint256",
      },
    ],
    name: "AttributeSwapAwarded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newFee",
        type: "uint256",
      },
    ],
    name: "CreatePlayerFeeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newAddress",
        type: "address",
      },
    ],
    name: "EquipmentRequirementsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "gameContract",
        type: "address",
      },
      {
        components: [
          { internalType: "bool", name: "record", type: "bool" },
          { internalType: "bool", name: "retire", type: "bool" },
          { internalType: "bool", name: "name", type: "bool" },
          { internalType: "bool", name: "attributes", type: "bool" },
          { internalType: "bool", name: "immortal", type: "bool" },
        ],
        indexed: false,
        internalType: "struct IPlayer.GamePermissions",
        name: "permissions",
        type: "tuple",
      },
    ],
    name: "GameContractPermissionsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalCharges",
        type: "uint256",
      },
    ],
    name: "NameChangeAwarded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "isPaused", type: "bool" },
    ],
    name: "PausedStateChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "enum IPlayer.Attribute",
        name: "decreaseAttribute",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum IPlayer.Attribute",
        name: "increaseAttribute",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "newDecreaseValue",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "newIncreaseValue",
        type: "uint8",
      },
    ],
    name: "PlayerAttributesSwapped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "strength",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "constitution",
        type: "uint8",
      },
      { indexed: false, internalType: "uint8", name: "size", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "agility", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "stamina", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "luck", type: "uint8" },
    ],
    name: "PlayerAttributesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "randomness",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "firstNameIndex",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "surnameIndex",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "strength",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "constitution",
        type: "uint8",
      },
      { indexed: false, internalType: "uint8", name: "size", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "agility", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "stamina", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "luck", type: "uint8" },
    ],
    name: "PlayerCreationComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "requester",
        type: "address",
      },
    ],
    name: "PlayerCreationRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "immortal", type: "bool" },
    ],
    name: "PlayerImmortalityChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      { indexed: false, internalType: "uint16", name: "kills", type: "uint16" },
    ],
    name: "PlayerKillUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "firstNameIndex",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "surnameIndex",
        type: "uint16",
      },
    ],
    name: "PlayerNameUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "retired", type: "bool" },
    ],
    name: "PlayerRetired",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "skinIndex",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "tokenId",
        type: "uint16",
      },
      { indexed: false, internalType: "uint8", name: "stance", type: "uint8" },
    ],
    name: "PlayerSkinEquipped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint8",
        name: "slotsAdded",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "totalSlots",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountPaid",
        type: "uint256",
      },
    ],
    name: "PlayerSlotsPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      { indexed: false, internalType: "uint16", name: "wins", type: "uint16" },
      {
        indexed: false,
        internalType: "uint16",
        name: "losses",
        type: "uint16",
      },
    ],
    name: "PlayerWinLossUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "adminInitiated",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "recoveryTimestamp",
        type: "uint256",
      },
    ],
    name: "RequestRecovered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "round",
        type: "uint256",
      },
      { indexed: false, internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "RequestedRandomness",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldCost",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newCost",
        type: "uint256",
      },
    ],
    name: "SlotBatchCostUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "playerId",
        type: "uint32",
      },
      { indexed: false, internalType: "uint8", name: "stance", type: "uint8" },
    ],
    name: "StanceUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldValue",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "VrfRequestTimeoutUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "BASE_PLAYER_SLOTS",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "attributeSwapCharges",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "to", type: "address" }],
    name: "awardAttributeSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "to", type: "address" }],
    name: "awardNameChange",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      { internalType: "uint16", name: "firstNameIndex", type: "uint16" },
      { internalType: "uint16", name: "surnameIndex", type: "uint16" },
    ],
    name: "changeName",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "bool", name: "refund", type: "bool" },
    ],
    name: "clearPendingRequestsForAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint32", name: "playerId", type: "uint32" },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
        ],
        internalType: "struct Fighter.PlayerLoadout",
        name: "loadout",
        type: "tuple",
      },
    ],
    name: "convertToFighterStats",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "weapon", type: "uint8" },
          { internalType: "uint8", name: "armor", type: "uint8" },
          { internalType: "uint8", name: "stance", type: "uint8" },
          {
            components: [
              { internalType: "uint8", name: "strength", type: "uint8" },
              { internalType: "uint8", name: "constitution", type: "uint8" },
              { internalType: "uint8", name: "size", type: "uint8" },
              { internalType: "uint8", name: "agility", type: "uint8" },
              { internalType: "uint8", name: "stamina", type: "uint8" },
              { internalType: "uint8", name: "luck", type: "uint8" },
            ],
            internalType: "struct Fighter.Attributes",
            name: "attributes",
            type: "tuple",
          },
        ],
        internalType: "struct IGameEngine.FighterStats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "createPlayerFeeAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "data", type: "bytes32" }],
    name: "decodePlayerData",
    outputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      {
        components: [
          {
            components: [
              { internalType: "uint8", name: "strength", type: "uint8" },
              { internalType: "uint8", name: "constitution", type: "uint8" },
              { internalType: "uint8", name: "size", type: "uint8" },
              { internalType: "uint8", name: "agility", type: "uint8" },
              { internalType: "uint8", name: "stamina", type: "uint8" },
              { internalType: "uint8", name: "luck", type: "uint8" },
            ],
            internalType: "struct Fighter.Attributes",
            name: "attributes",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint16",
                name: "firstNameIndex",
                type: "uint16",
              },
              { internalType: "uint16", name: "surnameIndex", type: "uint16" },
            ],
            internalType: "struct IPlayer.PlayerName",
            name: "name",
            type: "tuple",
          },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
          {
            components: [
              { internalType: "uint16", name: "wins", type: "uint16" },
              { internalType: "uint16", name: "losses", type: "uint16" },
              { internalType: "uint16", name: "kills", type: "uint16" },
            ],
            internalType: "struct Fighter.Record",
            name: "record",
            type: "tuple",
          },
        ],
        internalType: "struct IPlayer.PlayerStats",
        name: "stats",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      {
        components: [
          {
            components: [
              { internalType: "uint8", name: "strength", type: "uint8" },
              { internalType: "uint8", name: "constitution", type: "uint8" },
              { internalType: "uint8", name: "size", type: "uint8" },
              { internalType: "uint8", name: "agility", type: "uint8" },
              { internalType: "uint8", name: "stamina", type: "uint8" },
              { internalType: "uint8", name: "luck", type: "uint8" },
            ],
            internalType: "struct Fighter.Attributes",
            name: "attributes",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint16",
                name: "firstNameIndex",
                type: "uint16",
              },
              { internalType: "uint16", name: "surnameIndex", type: "uint16" },
            ],
            internalType: "struct IPlayer.PlayerName",
            name: "name",
            type: "tuple",
          },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
          {
            components: [
              { internalType: "uint16", name: "wins", type: "uint16" },
              { internalType: "uint16", name: "losses", type: "uint16" },
              { internalType: "uint16", name: "kills", type: "uint16" },
            ],
            internalType: "struct Fighter.Record",
            name: "record",
            type: "tuple",
          },
        ],
        internalType: "struct IPlayer.PlayerStats",
        name: "stats",
        type: "tuple",
      },
    ],
    name: "encodePlayerData",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      { internalType: "uint32", name: "skinIndex", type: "uint32" },
      { internalType: "uint16", name: "skinTokenId", type: "uint16" },
      { internalType: "uint8", name: "stance", type: "uint8" },
    ],
    name: "equipSkin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "equipmentRequirements",
    outputs: [
      {
        internalType: "contract IEquipmentRequirements",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "randomness", type: "uint256" },
      { internalType: "bytes", name: "dataWithRound", type: "bytes" },
    ],
    name: "fulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "gameContract", type: "address" },
    ],
    name: "gameContractPermissions",
    outputs: [
      {
        components: [
          { internalType: "bool", name: "record", type: "bool" },
          { internalType: "bool", name: "retire", type: "bool" },
          { internalType: "bool", name: "name", type: "bool" },
          { internalType: "bool", name: "attributes", type: "bool" },
          { internalType: "bool", name: "immortal", type: "bool" },
        ],
        internalType: "struct IPlayer.GamePermissions",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "getActivePlayerCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getCurrentAttributes",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "strength", type: "uint8" },
          { internalType: "uint8", name: "constitution", type: "uint8" },
          { internalType: "uint8", name: "size", type: "uint8" },
          { internalType: "uint8", name: "agility", type: "uint8" },
          { internalType: "uint8", name: "stamina", type: "uint8" },
          { internalType: "uint8", name: "luck", type: "uint8" },
        ],
        internalType: "struct Fighter.Attributes",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getCurrentName",
    outputs: [
      {
        components: [
          { internalType: "uint16", name: "firstNameIndex", type: "uint16" },
          { internalType: "uint16", name: "surnameIndex", type: "uint16" },
        ],
        internalType: "struct IPlayer.PlayerName",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getCurrentRecord",
    outputs: [
      {
        components: [
          { internalType: "uint16", name: "wins", type: "uint16" },
          { internalType: "uint16", name: "losses", type: "uint16" },
          { internalType: "uint16", name: "kills", type: "uint16" },
        ],
        internalType: "struct Fighter.Record",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getCurrentSkin",
    outputs: [
      {
        components: [
          { internalType: "uint32", name: "skinIndex", type: "uint32" },
          { internalType: "uint16", name: "skinTokenId", type: "uint16" },
        ],
        internalType: "struct Fighter.SkinInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getCurrentStance",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getFighterStats",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "weapon", type: "uint8" },
          { internalType: "uint8", name: "armor", type: "uint8" },
          { internalType: "uint8", name: "stance", type: "uint8" },
          {
            components: [
              { internalType: "uint8", name: "strength", type: "uint8" },
              { internalType: "uint8", name: "constitution", type: "uint8" },
              { internalType: "uint8", name: "size", type: "uint8" },
              { internalType: "uint8", name: "agility", type: "uint8" },
              { internalType: "uint8", name: "stamina", type: "uint8" },
              { internalType: "uint8", name: "luck", type: "uint8" },
            ],
            internalType: "struct Fighter.Attributes",
            name: "attributes",
            type: "tuple",
          },
        ],
        internalType: "struct IGameEngine.FighterStats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getNextSlotBatchCost",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getPendingRequest",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getPlayer",
    outputs: [
      {
        components: [
          {
            components: [
              { internalType: "uint8", name: "strength", type: "uint8" },
              { internalType: "uint8", name: "constitution", type: "uint8" },
              { internalType: "uint8", name: "size", type: "uint8" },
              { internalType: "uint8", name: "agility", type: "uint8" },
              { internalType: "uint8", name: "stamina", type: "uint8" },
              { internalType: "uint8", name: "luck", type: "uint8" },
            ],
            internalType: "struct Fighter.Attributes",
            name: "attributes",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint16",
                name: "firstNameIndex",
                type: "uint16",
              },
              { internalType: "uint16", name: "surnameIndex", type: "uint16" },
            ],
            internalType: "struct IPlayer.PlayerName",
            name: "name",
            type: "tuple",
          },
          {
            components: [
              { internalType: "uint32", name: "skinIndex", type: "uint32" },
              { internalType: "uint16", name: "skinTokenId", type: "uint16" },
            ],
            internalType: "struct Fighter.SkinInfo",
            name: "skin",
            type: "tuple",
          },
          { internalType: "uint8", name: "stance", type: "uint8" },
          {
            components: [
              { internalType: "uint16", name: "wins", type: "uint16" },
              { internalType: "uint16", name: "losses", type: "uint16" },
              { internalType: "uint16", name: "kills", type: "uint16" },
            ],
            internalType: "struct Fighter.Record",
            name: "record",
            type: "tuple",
          },
        ],
        internalType: "struct IPlayer.PlayerStats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "getPlayerOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "getPlayerSlots",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "getRequestStatus",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "bool", name: "fulfilled", type: "bool" },
      { internalType: "address", name: "owner", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "incrementKills",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "incrementLosses",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "incrementWins",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isPaused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "isPlayerImmortal",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "isPlayerRetired",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "isValidId",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "nameChangeCharges",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nameRegistry",
    outputs: [
      {
        internalType: "contract IPlayerNameRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "purchasePlayerSlots",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "recoverERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "recoverTimedOutRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "useNameSetB", type: "bool" }],
    name: "requestCreatePlayer",
    outputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "requestPending",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "requestedHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "playerId", type: "uint32" }],
    name: "retireOwnPlayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newFeeAmount", type: "uint256" },
    ],
    name: "setCreatePlayerFeeAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newAddress", type: "address" }],
    name: "setEquipmentRequirements",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "gameContract", type: "address" },
      {
        components: [
          { internalType: "bool", name: "record", type: "bool" },
          { internalType: "bool", name: "retire", type: "bool" },
          { internalType: "bool", name: "name", type: "bool" },
          { internalType: "bool", name: "attributes", type: "bool" },
          { internalType: "bool", name: "immortal", type: "bool" },
        ],
        internalType: "struct IPlayer.GamePermissions",
        name: "permissions",
        type: "tuple",
      },
    ],
    name: "setGameContractPermission",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOperator", type: "address" }],
    name: "setOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "paused", type: "bool" }],
    name: "setPaused",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      { internalType: "bool", name: "immortal", type: "bool" },
    ],
    name: "setPlayerImmortal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      { internalType: "bool", name: "retired", type: "bool" },
    ],
    name: "setPlayerRetired",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newCost", type: "uint256" }],
    name: "setSlotBatchCost",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      { internalType: "uint8", name: "stance", type: "uint8" },
    ],
    name: "setStance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newValue", type: "uint256" }],
    name: "setVrfRequestTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "skinRegistry",
    outputs: [
      {
        internalType: "contract IPlayerSkinRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "slotBatchCost",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "playerId", type: "uint32" },
      {
        internalType: "enum IPlayer.Attribute",
        name: "decreaseAttribute",
        type: "uint8",
      },
      {
        internalType: "enum IPlayer.Attribute",
        name: "increaseAttribute",
        type: "uint8",
      },
    ],
    name: "swapAttributes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "vrfRequestTimeout",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
